#!/usr/bin/env bash

# Shared VisionCraft tooling configuration. Keep defaults here so command
# scripts can compose the same paths, ports, and bundle identifiers.

VC_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_DIR="$(cd "$VC_LIB_DIR/.." && pwd)"
REPO_ROOT="${VISIONCRAFT_REPO_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd)}"

RUN_DIR="${VISIONCRAFT_RUN_DIR:-$REPO_ROOT/.run}"
CONTROL_PORT="${VISIONCRAFT_CONTROL_PORT:-19734}"
BRIDGE_PORT="${VISIONCRAFT_BRIDGE_PORT:-19735}"
CONTROL_URL="${VISIONCRAFT_CONTROL_URL:-http://127.0.0.1:${CONTROL_PORT}}"

HOST_PROJECT="${VISIONCRAFT_HOST_PROJECT:-$REPO_ROOT/mac-host/VisionCraftHost.xcodeproj}"
HOST_SCHEME="${VISIONCRAFT_HOST_SCHEME:-VisionCraftHost}"
HOST_DERIVED="${VISIONCRAFT_HOST_DERIVED:-$REPO_ROOT/mac-host/build}"
HOST_APP="${VISIONCRAFT_HOST_APP:-$HOST_DERIVED/Build/Products/Debug/VisionCraftHost.app}"

ALVR_CLIENT_PROJECT="${VISIONCRAFT_ALVR_CLIENT_PROJECT:-$REPO_ROOT/visionos-app/ALVRClient.xcodeproj}"
ALVR_CLIENT_SCHEME="${VISIONCRAFT_ALVR_CLIENT_SCHEME:-ALVRClient}"
ALVR_CLIENT_DERIVED="${VISIONCRAFT_ALVR_CLIENT_DERIVED:-$REPO_ROOT/visionos-app/build}"
ALVR_CLIENT_APP="${VISIONCRAFT_ALVR_CLIENT_APP:-$ALVR_CLIENT_DERIVED/Build/Products/Debug-xros/ALVRClient.app}"
ALVR_CLIENT_CORE="${VISIONCRAFT_ALVR_CLIENT_CORE:-$REPO_ROOT/visionos-app/ALVRClient/ALVRClientCore.xcframework}"
ALVR_CLIENT_BUNDLE_ID="${VISIONCRAFT_ALVR_CLIENT_BUNDLE_ID:-}"

MC_DIR="${VISIONCRAFT_MC_DIR:-$REPO_ROOT/minecraft/VivecraftMod}"
HOST_VENDOR="${VISIONCRAFT_HOST_VENDOR:-$REPO_ROOT/mac-host/Vendor/ALVRServerCore}"
SERVER_CORE_HEADER="${VISIONCRAFT_SERVER_CORE_HEADER:-$HOST_VENDOR/alvr_server_core.h}"
SERVER_CORE_DYLIB="${VISIONCRAFT_SERVER_CORE_DYLIB:-$HOST_VENDOR/libalvr_server_core.dylib}"
BETA_DIR="${VISIONCRAFT_BETA_DIR:-$RUN_DIR/beta}"
